
const carros = [
  {
    id: 1,
    nome: "Relâmpago McQueen",
    modelo: "Carro de Corrida",
    ano: 2006,
    cor: "Vermelho",
    qtdeVitorias: 7,
  },
  {
    id: 2,
    nome: "Mate",
    modelo: "Caminhão Reboque",
    ano: 1957,
    cor: "Marrom",
    qtdeVitorias: 0,
  },
  {
    id: 3,
    nome: "Doc Hudson",
    modelo: "Hudson Hornet",
    ano: 1951,
    cor: "Azul Marinho",
    qtdeVitorias: 3,
  },
  {
    id: 4,
    nome: "Sally Carrera",
    modelo: "Porsche 911",
    ano: 2002,
    cor: "Azul Claro",
    qtdeVitorias: 0,
  },
  {
    id: 5,
    nome: "Ramone",
    modelo: "Chevrolet Impala Lowrider",
    ano: 1959,
    cor: "Roxo",
    qtdeVitorias: 0,
  },
  {
    id: 6,
    nome: "Flo",
    modelo: "Show Car",
    ano: 1957,
    cor: "Verde Água",
    qtdeVitorias: 0,
  },
  {
    id: 7,
    nome: "Sargento",
    modelo: "Willys Jeep",
    ano: 1942,
    cor: "Verde Oliva",
    qtdeVitorias: 0,
  },
  {
    id: 8,
    nome: "Chick Hicks",
    modelo: "Carro de Corrida",
    ano: 2006,
    cor: "Verde Limão",
    qtdeVitorias: 1,
  },
  {
    id: 9,
    nome: "Cruz Ramirez",
    modelo: "Carro de Treinamento",
    ano: 2017,
    cor: "Amarelo",
    qtdeVitorias: 1,
  },
  {
    id: 10,
    nome: "Jackson Storm",
    modelo: "Carro de Corrida",
    ano: 2017,
    cor: "Cinza Chumbo",
    qtdeVitorias: 5,
  },
];

export default { carros }