const carros = [
    {
      id: 1,
      nome: "Relâmpago McQueen",
      modelo: "Carro de Corrida",
      ano: 2006,
      cor: "Vermelho",
      qtdeVitorias: 7,
      velocidadeMaxima: 320,
      equipe: "Rust-eze",
    },
    {
      id: 2,
      nome: "Mate",
      modelo: "Caminhão Reboque",
      ano: 1957,
      cor: "Marrom",
      qtdeVitorias: 0,
      velocidadeMaxima: 60,
      equipe: "Radiator Springs",
    },
    {
      id: 3,
      nome: "Doc Hudson",
      modelo: "Hudson Hornet",
      ano: 1951,
      cor: "Azul Marinho",
      qtdeVitorias: 3,
      velocidadeMaxima: 190,
      equipe: "Fabulous Hudson Hornet",
    },
    {
      id: 4,
      nome: "Sally Carrera",
      modelo: "Porsche 911",
      ano: 2002,
      cor: "Azul Claro",
      qtdeVitorias: 0,
      velocidadeMaxima: 210,
      equipe: "Radiator Springs",
    },
    {
      id: 5,
      nome: "Ramone",
      modelo: "Chevrolet Impala Lowrider",
      ano: 1959,
      cor: "Roxo",
      qtdeVitorias: 0,
      velocidadeMaxima: 130,
      equipe: "Ramone's House of Body Art",
    },
    {
      id: 6,
      nome: "Flo",
      modelo: "Show Car",
      ano: 1957,
      cor: "Verde Água",
      qtdeVitorias: 0,
      velocidadeMaxima: 110,
      equipe: "Flo's V8 Café",
    },
    {
      id: 7,
      nome: "Sargento",
      modelo: "Willys Jeep",
      ano: 1942,
      cor: "Verde Oliva",
      qtdeVitorias: 0,
      velocidadeMaxima: 90,
      equipe: "Radiator Springs",
    },
    {
      id: 8,
      nome: "Chick Hicks",
      modelo: "Carro de Corrida",
      ano: 2006,
      cor: "Verde Limão",
      qtdeVitorias: 1,
      velocidadeMaxima: 310,
      equipe: "Hostile Takeover Bank",
    },
    {
      id: 9,
      nome: "Cruz Ramirez",
      modelo: "Carro de Treinamento",
      ano: 2017,
      cor: "Amarelo",
      qtdeVitorias: 1,
      velocidadeMaxima: 340,
      equipe: "Dinoco",
    },
    {
      id: 10,
      nome: "Jackson Storm",
      modelo: "Carro de Corrida",
      ano: 2017,
      cor: "Cinza Chumbo",
      qtdeVitorias: 5,
      velocidadeMaxima: 350,
      equipe: "Ignitr",
    },
  ];

export default { carros }